### ISSUE TITLE
Typo in ActiveWrap example code in readme.md

### ISSUE THREAD

**Issue by martindederer** [zxbodya/router1-react#1]
The readme file states that the ActiveWrap component has the property "activeClassName". It is actually called "activeClass" in the source.

**Comment by martindederer** [comment]
Maybe this property should be named consistently in the Link and ActiveWrap component.

**Comment by zxbodya** [comment]
Yes, you are right - naming should be consistent. Thanks for hint.

Renamed property `activeClass` in `ActiveWrap` component to `activeClassName` to make it consistent with `Link` component, and to match samples in readme.

Released new verison `0.7` to npm.
